### ISSUE TITLE
Mise à jour du site

### ISSUE THREAD

**Issue by nokiiam** [JMounier/Aegina#309]
- garder le wiki à jour
- ajout de news avec les ajouts de nouveaux mobs 
- ajouts des news pour les issues quand elles sont terminé : 
- [x] Coffres et piège (#308 #304)
- [x] Refonte du combat et PVP et conquête (#301 #306) 
- [x] Histoire et boss final (#139 #299) 
- [x] Cristal et chef de meute (#305 #303 #300)
